/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.openjfx.javafxplugin") version "0.0.13"
    id("application")
}

javafx {
    version = "11.0.2"
    modules = listOf(
        "javafx.controls",
        "javafx.graphics",
        "javafx.fxml",
        "javafx.web",
        "javafx.media"
    )
}

application {
    mainClass.set("com.shinonometn.fx.demo.MainKt")
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-javafx:1.6.4")
}

dependencies {
    implementation(project(":toy-brick-fx"))
}
