/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("application")
}

application {

}

//mainClassName="com.shinonometn.fx.demo.MainKt"

dependencies {
    implementation(project(":toy-brick-fx"))
}
